from PySide6 import QtCore, QtGui, QtWidgets


class ScanProgressPanel(QtWidgets.QWidget):
    def __init__(self, on_pause, on_resume, on_restart, on_skip):
        super().__init__()
        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(40, 48, 40, 48)
        layout.setSpacing(32)

        self.seq_w = QtWidgets.QWidget()
        seq_l = QtWidgets.QVBoxLayout(self.seq_w)
        seq_l.setSpacing(12)
        seq_l.setContentsMargins(0, 0, 0, 0)
        self.slots = []
        for _ in range(3):
            slot = QtWidgets.QLabel("...")
            slot.setObjectName("hero_sub")
            slot.setStyleSheet("font-family: 'Consolas', monospace; font-size: 11px; color: rgba(255,255,255,0.15);")
            slot.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            self.slots.append(slot)
            seq_l.addWidget(slot)
        self.slots[1].setStyleSheet("font-family: 'Consolas', monospace; font-size: 13px; font-weight: 700; color: #007AFF;")
        layout.addWidget(self.seq_w)

        self.count_lbl = QtWidgets.QLabel("0 Videos Found")
        self.count_lbl.setStyleSheet("font-size: 20px; font-weight: 800; color: #FFF;")
        self.count_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(self.count_lbl)

        self.bar = QtWidgets.QProgressBar()
        self.bar.setRange(0, 0)
        self.bar.setFixedHeight(3)
        layout.addWidget(self.bar)

        self.ctrl_stack = QtWidgets.QStackedWidget()
        self.ctrl_stack.setMaximumWidth(380)
        self.ctrl_stack.setMinimumHeight(116)
        layout.addWidget(self.ctrl_stack, alignment=QtCore.Qt.AlignmentFlag.AlignCenter)

        active = QtWidgets.QWidget()
        active_l = QtWidgets.QHBoxLayout(active)
        active_l.setContentsMargins(0, 0, 0, 0)
        active.setMinimumHeight(116)
        self.pause_btn = QtWidgets.QPushButton(" Stop")
        self.pause_btn.setObjectName("secondary")
        self.pause_btn.setIcon(QtGui.QIcon("src/ui/assets/icons/stop.svg"))
        self.pause_btn.setIconSize(QtCore.QSize(18, 18))
        self.pause_btn.setFixedSize(160, 44)
        self.pause_btn.clicked.connect(on_pause)
        active_l.addStretch()
        active_l.addWidget(self.pause_btn)
        active_l.addStretch()
        self.ctrl_stack.addWidget(active)

        paused = QtWidgets.QWidget()
        paused_l = QtWidgets.QVBoxLayout(paused)
        paused_l.setSpacing(0)
        paused_l.setContentsMargins(0, 0, 0, 0)
        paused.setMinimumHeight(116)

        top_row = QtWidgets.QWidget()
        top_row_l = QtWidgets.QHBoxLayout(top_row)
        top_row_l.setContentsMargins(0, 0, 0, 0)
        self.resume_btn = QtWidgets.QPushButton(" Resume")
        self.resume_btn.setObjectName("primary")
        self.resume_btn.setIcon(QtGui.QIcon("src/ui/assets/icons/play.svg"))
        self.resume_btn.setFixedHeight(50)
        self.resume_btn.clicked.connect(on_resume)
        top_row_l.addWidget(self.resume_btn)
        paused_l.addWidget(top_row)
        paused_l.addSpacing(10)

        bottom_row = QtWidgets.QWidget()
        bottom_row_l = QtWidgets.QHBoxLayout(bottom_row)
        bottom_row_l.setContentsMargins(0, 0, 0, 0)
        bottom_row_l.setSpacing(12)
        self.restart_btn = QtWidgets.QPushButton(" Restart")
        self.restart_btn.setObjectName("secondary")
        self.restart_btn.setFixedHeight(42)
        self.restart_btn.setIcon(QtGui.QIcon("src/ui/assets/icons/restart.svg"))
        self.restart_btn.setIconSize(QtCore.QSize(18, 18))
        self.restart_btn.clicked.connect(on_restart)
        self.skip_btn = QtWidgets.QPushButton(" Skip Full Scan")
        self.skip_btn.setObjectName("secondary")
        self.skip_btn.setFixedHeight(42)
        self.skip_btn.setIcon(QtGui.QIcon("src/ui/assets/icons/skip.svg"))
        self.skip_btn.setIconSize(QtCore.QSize(18, 18))
        self.skip_btn.clicked.connect(on_skip)
        bottom_row_l.addWidget(self.restart_btn)
        bottom_row_l.addWidget(self.skip_btn)
        paused_l.addWidget(bottom_row)
        paused_l.addStretch()
        self.ctrl_stack.addWidget(paused)

    def reset(self):
        self.pause_btn.setText(" Stop")
        self.pause_btn.setEnabled(True)
        self.count_lbl.setText("0 Videos Found")
        self.bar.setRange(0, 0)
        for slot in self.slots:
            slot.setText("...")
        self.ctrl_stack.setCurrentIndex(0)


class ImportProgressPanel(QtWidgets.QWidget):
    def __init__(self, on_stop):
        super().__init__()
        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(40, 48, 40, 48)
        layout.setSpacing(32)

        self.seq_w = QtWidgets.QWidget()
        seq_l = QtWidgets.QVBoxLayout(self.seq_w)
        seq_l.setSpacing(12)
        seq_l.setContentsMargins(0, 0, 0, 0)
        self.slots = []
        for _ in range(3):
            slot = QtWidgets.QLabel("...")
            slot.setObjectName("hero_sub")
            slot.setStyleSheet("font-family: 'Consolas', monospace; font-size: 11px; color: rgba(255,255,255,0.15);")
            slot.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            self.slots.append(slot)
            seq_l.addWidget(slot)
        self.slots[1].setStyleSheet("font-family: 'Consolas', monospace; font-size: 13px; font-weight: 700; color: #007AFF;")
        layout.addWidget(self.seq_w)

        self.count_lbl = QtWidgets.QLabel("0 items queued")
        self.count_lbl.setStyleSheet("font-size: 20px; font-weight: 800; color: #FFF;")
        self.count_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(self.count_lbl)

        self.bar = QtWidgets.QProgressBar()
        self.bar.setRange(0, 0)
        self.bar.setFixedHeight(3)
        layout.addWidget(self.bar)

        controls = QtWidgets.QWidget()
        controls_l = QtWidgets.QHBoxLayout(controls)
        controls_l.setContentsMargins(0, 0, 0, 0)
        controls.setMinimumHeight(116)
        self.stop_btn = QtWidgets.QPushButton(" Stop Import")
        self.stop_btn.setObjectName("secondary")
        self.stop_btn.setIcon(QtGui.QIcon("src/ui/assets/icons/stop.svg"))
        self.stop_btn.setIconSize(QtCore.QSize(18, 18))
        self.stop_btn.setFixedSize(160, 44)
        self.stop_btn.clicked.connect(on_stop)
        controls_l.addStretch()
        controls_l.addWidget(self.stop_btn)
        controls_l.addStretch()
        layout.addWidget(controls, alignment=QtCore.Qt.AlignmentFlag.AlignCenter)

    def reset(self, queued_count: int):
        self.stop_btn.setEnabled(True)
        self.count_lbl.setText(f"{queued_count} items queued")
        self.bar.setRange(0, 0)
        self.slots[0].setText("Preparing transfer...")
        self.slots[1].setText("Waiting for first file...")
        self.slots[2].setText("Transfer stays active even if Windows opens a copy dialog.")
